version: "2"
plugins:
  checkstyle:
    enabled: true
  codenarc:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  pmd:
    enabled: true
  shellcheck:
    enabled: true
  sonar-java:
    enabled: true
    config:
      tests_patterns:
        - applet/src/test/
exclude_patterns:
  - "applet/src/test/"