version: ~> 1.0
language: java
os: linux
dist: xenial
jdk:
  - openjdk8
env:
  global:
    - CC_TEST_REPORTER_ID=2ff901ea9f54de86ddb0b0c37b950e09a1a7958edcdf472230be713b5dad684b
    - JACOCO_SOURCE_PATH=applet/src/main/java
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  # https://docs.travis-ci.com/user/languages/java/#projects-using-gradle
  - ./gradlew check --info --stacktrace
  # TODO removed while we use bouncycastle instead of JCMathlib which does not work now.
  # - ./gradlew buildJavaCard --info --stacktrace
after_script:
  - ./cc-test-reporter format-coverage applet/build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage
