language: java
jdk:
  - openjdk8
  - openjdk11
script:
  # https://docs.travis-ci.com/user/languages/java/#projects-using-gradle
  - ./gradlew check --info --stacktrace
  - ./gradlew buildJavaCard --info --stacktrace
