language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk11
script:
  # https://docs.travis-ci.com/user/languages/java/#projects-using-gradle
  - ./gradlew check --info
  - ./gradlew buildJavaCard --info